# docker-compose.yml
version: "3"

services:
  # MySQL database
  db:
    image: mariadb
    restart: unless-stopped
    container_name: wp-passkeys-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Wordpress
  wp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: wp-passkeys-app
    environment:
      WORDPRESS_DB_HOST: wp-passkeys-db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_DEBUG_LOG: 1
      WORDPRESS_DEBUG_DISPLAY: 1
      XDEBUG_CONFIG: "remote_host=192.168.0.31"
      PHP_IDE_CONFIG: "serverName=localhost"
    volumes:
      - ./wp:/var/www/html
      - ./:/var/www/html/wp-content/plugins/wp-passkeys
      - ./certs:/etc/apache2/ssl
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - db
# Make network name pretty
networks:
  default:
    name: wp-passkeys-network

# Persist DB and WordPress data across containers
volumes:
  db-data:
  wp-data:
